language: ruby
rvm:
    - 2.1
script: "bundle exec jekyll build"
notifications:
    slack: k4m5c:zXYOww6fEBsrgwY4JkE5BCXt

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
